### ISSUE TITLE
infi.dtypes.hctl not listed as dependency

### ISSUE THREAD

**Issue by ghost** [Infinidat/infi.iscsiapi#4]
When trying to run this on Linux, I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/infi/iscsiapi/linux.py", line 259, in login_all
    self.login(target, endpoint, auth)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/infi/iscsiapi/linux.py", line 249, in login
    if self._session_already_active(target, endpoint) is None:
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/infi/iscsiapi/linux.py", line 195, in _session_already_active
    for session in self.get_sessions(target=target):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/infi/iscsiapi/linux.py", line 272, in get_sessions
    sessions = self._get_sessions_from_sysfs()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/infi/iscsiapi/linux.py", line 123, in _get_sessions_from_sysfs
    for target_iqn, target_endpoint, source_ip, source_iqn, uid, hct in self._iter_sessions_in_sysfs():
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/infi/iscsiapi/linux.py", line 69, in _iter_sessions_in_sysfs
    from infi.dtypes.hctl import HCT
ModuleNotFoundError: No module named 'infi.dtypes.hctl'
```

**Comment by wiggin15** [comment]
Thanks. We will add this dependency.
